fix initialize script

diff --git a/vmware/templates/initialize b/vmware/templates/initialize
--- a/vmware/templates/initialize
+++ b/vmware/templates/initialize
@@ -1,14 +1,21 @@
 #!/bin/ksh
 
-# this script should be run only one time. 
+# this script should be run only one time.
 # If any of the configurations are in place, the script should end
-# it is supposed to be idempotent so if it's run again, it should just 
+# it is supposed to be idempotent so if it's run again, it should just
 # exit with, 'already in place'
 
-HERE=$(pwd)
-HOSTNAME=$(hostname|cut -f1 -d.)
+if [[ -z ${1} ]]
+then
+  echo "Error: Missing the service name"
+  ls -l
+  exit 1
+fi
 
-for i in $(find $HOSTNAME  -type d -print)
+HERE=$(pwd)
+SERVICE=${1}
+
+for i in $(find ${SERVICE}  -type d -print)
 do
   cd ${i}
 
@@ -22,8 +29,4 @@ do
   cd ${HERE}
 
 done
-
-virsh -c qemu:///system list --all
-
-virsh -c qemu:///system pool-list --all
 
